media: public/carousel
content:
  - name: about
    label: About
    path: content/about.json
    type: file
    format: json
    fields:
      - {
          name: bio,
          label: Bio,
          type: rich-text,
          options: { format: html, image: false },
        }
      - { name: clients, label: Clients, type: string }
      - { name: exhibitions, label: Exhibitions, type: string }
      - { name: talks, label: Talks, type: string }
      - { name: credits, label: Credits, type: string }
  - name: carousel
    label: Carousel
    type: collection
    path: content/slides
    filename: slide-{primary}.json
    format: json
    subfolders: false
    view:
      fields: [order, line1, line2, line3]
      primary: order
      sort: [order]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: line1, label: First Line, type: string }
      - { name: line2, label: Second Line, type: string }
      - { name: line3, label: Third Line, type: string }
      - {
          name: src,
          label: Image,
          type: image,
          list: false,
          options:
            {
              input: public/carousel,
              output: /carousel,
              extensions: jpg,
              jpeg,
              png,
            },
          description: "If a video is provided, this is still required as a fallback",
        }
      - {
          name: videoId,
          label: Video,
          type: string,
          list: false,
          description: "This should be the video ID from Vimeo",
        }
  - name: projects
    label: Projects
    type: collection
    path: content/projects
    filename: project-{primary}.json
    format: json
    subfolders: false
    view:
      fields: [order, title, src]
      primary: order
      sort: [order]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - name: thumbnail
        label: Featured media
        type: object
        fields:
          - name: image
            label: Thumbnail Image
            type: image
            description: "If a video is provided, this is still required as a fallback"
            options:
              {
                input: public/projects,
                output: /projects,
                extensions: jpg,
                jpeg,
                png,
              }
          - name: video
            label: Video
            type: string
            description: "Video ID from Vimeo"
      - { name: title, label: Title, type: string }
      - {
          name: description,
          label: Description,
          type: rich-text,
          options: { format: html, image: false },
        }
      - name: media
        label: Media
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image
            description: "If a video is provided, this is still required as a fallback"
            options:
              {
                input: public/projects,
                output: /projects,
                extensions: jpg,
                jpeg,
                png,
              }
          - name: video
            label: Video
            type: string
            description: "Video ID from Vimeo"
          - name: hasAudio
            label: Video has audio?
            type: boolean
            description: "Allow user to unmute video"
