media: public/carousel
content:
  - name: carousel
    label: Carousel
    type: collection
    path: content/slides
    filename: slide-{primary}.json
    format: json
    subfolders: false
    view:
      fields: [ order, line1 ]
      primary: order
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: line1, label: First Line, type: string }
      - { name: line2, label: First Line, type: string }
      - { name: line3, label: First Line, type: string }
      - { name: src, label: Image, type: image, list: true, options: { path: public/carousel, extensions: jpg, jpeg, png} }