media: public/carousel
content:
  - name: carousel
    label: Carousel
    type: collection
    path: content/slides
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: line1, label: First Line, type: string }
      - { name: line2, label: First Line, type: string }
      - { name: line3, label: First Line, type: string }
      - { name: src, label: Image, type: image, list: true, options: { path: public/carousel, extensions: jpg, jpeg, png} }