media: public/carousel
content:
  - name: carousel
    label: Carousel
    type: collection
    path: content/slides
    filename: slide-{primary}.json
    format: json
    subfolders: false
    view:
      fields: [ order ]
      primary: order
      sort: [ order, line1 ]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: line1, label: First Line, type: string }
      - { name: line2, label: Second Line, type: string }
      - { name: line3, label: Third Line, type: string }
      - { name: src, label: Image, type: image, list: false, options: { input: public/carousel, output: /carousel, extensions: jpg, jpeg, png } }